import './globals.css';
import {ReactNode} from 'react';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import GithubCorner from '../src/components/github-corner/GithubCorner';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout(props: {children: ReactNode; modal: ReactNode}) {
    return (
        <html lang="ko">
            <body>
                <GithubCorner />
                {props.children}
                {props.modal}
            </body>
        </html>
    );
}
